#This workflow creates our exe file for windows, mac and linux
#inspired by https://patriksvensson.se/posts/2020/03/creating-release-artifacts-with-github-actions
name: Executable Release of Chirp
run-name: ${{ github.actor }} is publishing a new version of "Chirp" by Group 30

on: 
  push:
    tags:
      - '*.*.*' #pattern som release tag matcher
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0 --always )
          release_name="Chirp-$tag-${{ matrix.target }}"

          dotnet publish src/ChirpWeb/ChirpWeb.csproj --runtime "${{ matrix.target }}" -c Release --self-contained true
               
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/Chirp.exe"
          else
            7z a -tzip "${release_name}.zip" "./${release_name}/Chirp"
          fi
          
          rm -r "$release_name"

      #- name: Restore dependencies
      #  run: dotnet restore
        
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp-*" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}